"""empty message

Revision ID: 55b9e3fb2ee7
Revises: 49c130bd7cd7
Create Date: 2020-07-27 10:17:22.246367

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55b9e3fb2ee7'
down_revision = '49c130bd7cd7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('district', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'district')
    # ### end Alembic commands ###
