"""empty message

Revision ID: 49c130bd7cd7
Revises: 16c19fe1fb1d
Create Date: 2020-07-26 20:01:21.596164

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49c130bd7cd7'
down_revision = '16c19fe1fb1d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('district', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'district')
    # ### end Alembic commands ###
